services:
  db:
    container_name: 69-s2-db
    image: postgres:16-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: kanawat
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mydatabase
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  admin:
    container_name: 69-s2-admin
    image: dpage/pgadmin4:latest
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kanawat-sr@rmutp.ac.th
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    volumes:
      - ./data-pgadmin:/var/lib/pgadmin

  app:
    container_name: 69-s2-app
    image: prawee/strapi
    ports:
      - "9092:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=mydatabase
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=kanawat
      - DATABASE_PASSWORD=12345678
    depends_on:
      - db